version: '3.8'

services:
  # API Server
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: forel-api-server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=./data/forel.db
      - ADMIN_CODE=0202
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=5242880
      - ALLOWED_ORIGINS=https://forelrest.com,https://telegram.forelrest.com,http://localhost:3000,http://localhost:5173,http://localhost:8080
      - TELEGRAM_BOT_TOKEN=8489499457:AAEYJsk8jN3qynY2J4DoPSlqU1ghMdwlbSQ
      - TELEGRAM_ADMIN_CHAT_ID=your-admin-chat-id
    volumes:
      - ./api-server/data:/app/data
      - ./api-server/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - forel-network

  # Telegram Bot
  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: forel-telegram-bot
    environment:
      - BOT_TOKEN=8489499457:AAEYJsk8jN3qynY2J4DoPSlqU1ghMdwlbSQ
      - WEBAPP_URL=https://telegram.forelrest.com
      - API_URL=https://forelrest.com
    depends_on:
      - api-server
    restart: unless-stopped
    networks:
      - forel-network

  # Web Application (forelrest.com)
  web-app:
    build:
      context: ./my-project-web
      dockerfile: Dockerfile
    container_name: forel-web-app
    ports:
      - "8080:80"
    depends_on:
      - api-server
    restart: unless-stopped
    networks:
      - forel-network

  # Telegram WebApp (telegram.forelrest.com)
  telegram-webapp:
    build:
      context: ./my-project
      dockerfile: Dockerfile
    container_name: forel-telegram-webapp
    ports:
      - "8081:80"
    depends_on:
      - api-server
    restart: unless-stopped
    networks:
      - forel-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: forel-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx-single-server.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - ./ssl:/etc/ssl/private:ro
    depends_on:
      - api-server
      - web-app
      - telegram-webapp
    restart: unless-stopped
    networks:
      - forel-network

networks:
  forel-network:
    driver: bridge
