version: '3.8'

services:
  # API Server
  api-server:
    build:
      context: ../api-server
      dockerfile: Dockerfile
    container_name: forel-api-server
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=./data/forel.db
      - ADMIN_CODE=0202
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=5242880
      - ALLOWED_ORIGINS=https://forelrest.com,https://telegram.forelrest.com,http://localhost:3000,http://localhost:5173,http://localhost:8080
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_CHAT_ID=${TELEGRAM_ADMIN_CHAT_ID}
    volumes:
      - ../api-server/data:/app/data
      - ../api-server/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - forel-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Telegram Bot
  telegram-bot:
    build:
      context: ../telegram-bot
      dockerfile: Dockerfile
    container_name: forel-telegram-bot
    environment:
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBAPP_URL=https://telegram.forelrest.com
      - API_URL=https://forelrest.com
    depends_on:
      api-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - forel-network

  # Web Application (forelrest.com)
  web-app:
    build:
      context: ../my-project-web
      dockerfile: Dockerfile
    container_name: forel-web-app
    depends_on:
      api-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - forel-network

  # Telegram WebApp (telegram.forelrest.com)
  telegram-webapp:
    build:
      context: ../my-project
      dockerfile: Dockerfile
    container_name: forel-telegram-webapp
    depends_on:
      api-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - forel-network

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: forel-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-single-server.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - ./ssl:/etc/ssl/private:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api-server
      - web-app
      - telegram-webapp
    restart: unless-stopped
    networks:
      - forel-network

networks:
  forel-network:
    driver: bridge
