FROM node:18-alpine

# Создаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости (включая devDependencies)
RUN npm ci

# Копируем исходный код
COPY . .

# Устанавливаем права доступа
RUN chown -R node:node /app
USER node

# Запускаем бота в режиме разработки
CMD ["npm", "run", "dev"]
